CGUC/skybunk-server

README.md
Found a few typos in the readme, proposing fix.
=> Fixed ReadMe typos

API/app.js
This didn't make sense before but now it should (hopefully)
=> Fix the comments in example so it makes sense

API/helpers/populate.js, README.md
Once all the database transactions finish, disconnect from the database, which ends the script.
Also add some output so it looks like it does something
=> Fix the populate.js script so it actually stops running

API/package-lock.json, API/package.json, API/test/exampleTest.js
- mocha 5.2.0
- chai 4.1.2
- sinon 5.0.10
Creates test folder for holding server-side unit tests, adds example test and description of the testing framework with some useful reading material.
=> Adds unit testing framework with Mocha and Chai

grapp/activities/channels.jsx, grapp/components/ContentBar.jsx, grapp/components/Navbar.jsx
Think it'd be good to adopt something like this to keep things semi-organised off the bat, the idea is that `components` will be reused across `activities`, which are the specific screens the user will interact with.
=> Simple folder layout

controllers/userController.js, models/User.js, package-lock.json, package.json
Allows server to handle file uploads for profile pictures as multipart form data
=> Extend user controller to update user profile picture

controllers/userController.js, models/User.js
Adds route and method to get all the posts of the channels a user is subscribed to
=> Add ability to get posts from a users subbed channels

controllers/userController.js, helpers/notificationManager.js, models/Channels.js, models/Posts.js, models/User.js, package-lock.json, package.json
Uses https://github.com/expo/exponent-server-sdk-node to send notifications out to devices. 
Upon post creation, find all users subscribed to the channels sharing the tags of the post and send thhem a notif
Upon comment creation, send notif to all users subscribed to that post
=> Add ability to dispatch notifications

helpers/notificationManager.js
=> fix big oopsie

controllers/channelController.js, controllers/postController.js, controllers/userController.js, models/Channels.js, models/Posts.js, models/User.js, package-lock.json, package.json
all queries to get posts now tags a 'page' parameter in the header specifying which page to get, with 15 posts per page
=> Paginate post queries, 15 posts per page

controllers/userController.js, models/ProfilePicture.js, models/User.js
If the user has no profile picture use the default picture
=> Use default image if user has no profile pic

app.js, controllers/notificationsController.js, controllers/userController.js, helpers/notificationManager.js, helpers/scripts/create_channel.js, models/Channels.js, models/Notification.js, models/Posts.js, models/User.js
Creates a model to represent notifications, and before dispatching any notifications it first saves the notification onto the user. 
When retrieving the logged in user, also populate their notifications. Currently limited to only the last 20 notifs
Also adds a route to mark notifications as seen
=> Save notifications on user model

controllers/userController.js, helpers/notificationManager.js, models/User.js, package-lock.json
Just adds an endpoint which marks all notifications as seen for a user
=> Endpoint to mark all notifications for user as seen

helpers/scripts/change_password.js
Adds a script to change a users password
=> Change password script

README.md, controllers/userController.js, helpers/jobScheduler.js, helpers/scripts/copy_prod_data.js, models/User.js, package.json
Adding a feature to see don information such as location, phone number, if they are on, and if they are on late supper. There will be a related PR in skybunk-mobile (with screenshots and such), but I haven't implemented the feature on the website version yet. Full list of feature changes are below:
-added donInfo field, which includes information of if the don is on, on late supper, location, and an automatic clock-out feature so dons don't have to remember to turn themselves off
-Added phone number to info fields. This was a necessity for dons so people can text/call them, but just added the field in for everyone for easy communication outside skybunk
-Added the agenda module to schedule events for the clock-out feature. Seems like a pretty cool library, and could be useful for future …
=> Added don schedules!

controllers/userController.js
Bug that causes dons not to be able to turn themselves on... Just disabling the timeout feature, which is the root cause of the issue it seems.
=> Fixing don bug

models/User.js
This is a tiny one-line fix that makes username matching case insensitive.
As a side note: Should the username have some format validation? I've seen a few interesting usernames that use whitespace and emojis.
=> Case insensitive usernames

README.md
- Who cares what node modules we're using other than express & mongoose
- `I` -> `we`
- Step 4 of set up was redundant since it's in step 5 anyways- so doing both steps might lead you to download MongoDB twice
=> Slight tweaks to readme

controllers/channelController.js, controllers/postController.js, controllers/userController.js
Privatize the user data, since there can be sensitive information such as addresses, locations, phone numbers, etc.
This PR is NOT backwards compatible. All users will need to update their apps for this to work, so this should be delayed a couple weeks to a month after the front end PR is merged, and a skybunk post should be made inform users.
front end PR: https://github.com/CGUC/skybunk-mobile/pull/143
#63
=> Make user data private

.circleci/config.yml
Tests were failing due to older version of node
=> Update circleci config to use latest version of node

controllers/postController.js, helpers/formatters.js, models/Media/Poll.js
Adds relevant endpoints to:
- Add poll to a post
- Vote on a poll
- Add an option to a poll
- Get poll from post
Original PR: https://github.com/picklechips/skybunk-server/pull/2
=> Add endpoints to manage polls on a post

controllers/channelController.js, controllers/userController.js, helpers/authorization.js, models/Channels.js, models/User.js
Updates/Adds endpoints to Edit/Delete/Create users and channels if user is an admin.
Also fixes some bugs/security vulnerabilities
=> Add relevant endpoints for admin tools

controllers/postController.js, models/Media/Poll.js, test/models/poll.test.js
Allow admins, creators of options, and poll authors to delete options in polls
=> Polls - delete option endpoint

README.md
At some point this should probably all be moved into a wiki instead of a long README, but I'm feeling lazy tonight. Please give input, since some of this newer architecture I don't fully understand
=> Updated README with server documentation

Procfile, controllers/postController.js, models/Media/Media.js, models/Media/Poll.js, models/Posts.js, package.json, test/models/media.test.js, test/models/poll.test.js
This goes along with mobile PR  https://github.com/CGUC/skybunk-mobile/pull/202
Changes:
-Remove title field from poll; use post content instead. There was no reason to have both the poll title and post content, so to make it easier to maintain I changed it to only be the 1 field. I verified this with @MirandaZhou to make sure that would be fine.
-Actually implemented all of the media stuff. Since the mobile PR had to deal with these end points a lot, I decided now would be a good time to rewrite this properly and get rid of the legacy code.
-Added the ability to delete media from preexisting posts.
=> Media update and other fun changes

app.js, controllers/analyticsController.js, models/Channels.js, models/Posts.js, models/User.js
Basically just adds a bunch of queries to the database for various metrics that the server can then return in JSON format. The new route is specified in `controllers/analyticsController.js`, and is restricted to admins. This endpoint is intended to be used by the `admin-tools` front-end.
=> Add an analytics endpoint to the server

config/options.js, controllers/userController.js, helpers/adminHelper.js, helpers/authorization.js, helpers/notificationManager.js, helpers/passwordReset.js, models/Channels.js, models/Posts.js, models/User.js, package-lock.json, package.json
The version of sharp we were using was incompatible with the version of node on CircleCI. This was fixed in version 0.23.2 (https://github.com/lovell/sharp/issues/1909)
Lets just bump it to the latest version. (0.24.0)
Note: Now that CI is running normally again there was a bunch of linting issues in previously force-merged commits... This fixes them too :'(
=> Fix Failing CI (Bump sharp to v0.24.0)
